name: test-fe

on:
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      react_changed: ${{ steps.dorm_react.outputs.changed }}
      angular_changed: ${{ steps.dorm_angular.outputs.changed }}

    steps:
      - uses: actions/checkout@v3

      - run: git fetch origin main

      - id: dorm_react
        name: Check if dorm-react has been changed
        run: >
          if grep -q "^dorm-fe/react/" <<< $(git diff --name-only origin/main --) ;
          then echo "changed=true" >> $GITHUB_OUTPUT;
          else echo "changed=false" >> $GITHUB_OUTPUT;
          fi

      - id: dorm_angular
        name: Check if dorm-angular has been changed
        run: >
          if grep -q "^dorm-fe/angular/" <<< $(git diff --name-only origin/main --) ;
          then echo "changed=true" >> $GITHUB_OUTPUT;
          else echo "changed=false" >> $GITHUB_OUTPUT;
          fi          

  test-fe:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: check
    env:
      react_changed: ${{ needs.check.outputs.react_changed }}
      angular_changed: ${{ needs.check.outputs.angular_changed }}

    steps:
      - name: No changes detected
        if: ${{ react_changed == 'false' && angular_changed == 'false' }}
        run: echo "No changes, nothing to do ¯\_(ツ)_/¯"

      - name: Checkout branch
        if: ${{ react_changed == 'true' || angular_changed == 'true' }}
        uses: actions/checkout@v3

      - name: Install react dependencies
        if: ${{ react_changed == 'true' }}
        working-directory: ./dorm-fe/react
        run: npm install

      - name: Run react tests
        if: ${{ react_changed == 'true' }}
        working-directory: ./dorm-fe/react
        run: npm run test:ci

      - name: Install angular dependencies
        if: ${{ angular_changed == 'true' }}
        working-directory: ./dorm-fe/angular
        run: npm install

      - name: Run angular tests
        if: ${{ angular_changed == 'true' }}
        working-directory: ./dorm-fe/angular
        run: npm run test:ci