name: test-be

on:
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      be_changed: ${{ steps.dorm_be.outputs.changed }}

    steps:
      - uses: actions/checkout@v3

      - run: git fetch origin main

      - id: dorm_be
        name: Check if dorm-be has been changed
        run: >
          if grep -q "^dorm-be/" <<< $(git diff --name-only origin/main --) ;
          then echo "changed=true" >> $GITHUB_OUTPUT;
          else echo "changed=false" >> $GITHUB_OUTPUT;
          fi

  test-be:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: check

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: dorm
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        ports:
          - "5432:5432"

    steps:
      - name: No changes detected
        if: ${{ needs.check.outputs.be_changed == 'false' }}
        run: echo "No changes, nothing to do ¯\_(ツ)_/¯"

      - name: Checkout main
        if: ${{ needs.check.outputs.be_changed == 'true' }}
        uses: actions/checkout@v3

      - name: Install JDK 17
        if: ${{ needs.check.outputs.be_changed == 'true' }}
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Run tests
        if: ${{ needs.check.outputs.be_changed == 'true' }}
        working-directory: ./dorm-be
        run: >
          ./gradlew test 
          -PcliArgs='-Dspring.datasource.username=test -Dspring.datasource.password=test'
          --no-daemon